# Generated by Django 4.1.3 on 2022-11-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='descripton',
            new_name='description',
        ),
    ]
